### PR TITLE
Add a CPRNG to the ABI

### PR DESCRIPTION
**Pull request by g2p**

### CODE REVIEW

**Comment by lachlansneff** [comment]
Now that we have `cprng_fill`, do you think we should remove the `random_fill` abi?

**Comment by g2p** [comment]
They fulfill different purposes.
random_fill makes no security guarantee, and as a consequence will be more
likely to be available. It is also a very fast option, whereas seeding the
CPRNG can be slow.
Some applications may also wish to run their own, even faster PRNG, and
seed it from whatever works if there is no security requirement.

**Review by lachlansneff — APPROVED** [review]
Looks good to me!

**Comment by g2p** [comment]
Thank you!
Looking forward to making use of this.

**Pull request merged**
